package exception

import "testing"

func Test_tryDefer(t *testing.T) {
	tryDefer()
}
